# Generated by Django 4.0.6 on 2022-09-13 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.CharField(max_length=50)),
                ('codigo_qr', models.ImageField(upload_to='')),
                ('estado', models.CharField(max_length=50)),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.PositiveBigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('numero_contacto', models.PositiveBigIntegerField()),
                ('direccion', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=50)),
                ('departameno', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('certificaciones', models.CharField(max_length=250)),
                ('rol', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(default=datetime.date.today)),
                ('fecha_muerte', models.DateField()),
                ('peso', models.FloatField()),
                ('estado', models.TextField()),
                ('id_granja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.CharField(max_length=300)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='id_Res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.res'),
        ),
        migrations.CreateModel(
            name='Ficha_Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(default=datetime.date.today)),
                ('direccion_recepcion', models.CharField(max_length=200)),
                ('temperatura', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
                ('comentarios', models.CharField(max_length=300)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.producto')),
                ('id_receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.proveedor')),
            ],
        ),
    ]
