# Generated by Django 4.0.6 on 2022-10-26 02:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traceFoodApp', '0002_rename_id_res_producto_id_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='departameno',
            new_name='departamento',
        ),
        migrations.AddField(
            model_name='ficha_recepcion',
            name='id_res',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.res'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contrasena',
            field=models.CharField(default='12345', max_length=15),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='usuario',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AddField(
            model_name='reporte',
            name='calificacion',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_reporte',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
