# Generated by Django 4.0.6 on 2022-11-15 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traceFoodApp', '0004_alter_proveedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_planta',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='traceFoodApp.proveedor'),
        ),
    ]
