# Generated by Django 4.1.1 on 2022-10-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='id_producto',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
