# Generated by Django 4.0.6 on 2022-10-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TraceApp', '0002_remove_producto_id_producto_id_producto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='User',
        ),
    ]
