# Generated by Django 4.0.6 on 2022-10-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TraceApp', '0003_rename_proveedor_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Proveedor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
